### ISSUE TITLE
最近clash本地直连一直超时，关闭mosdns后无问题

### ISSUE THREAD

**Issue by q259490476** [Journalist-HK/mosdns-config#4]
现在遇到两个问题：
1.mosdns日志里显示上游服务器不可用
![image](https://github.com/Journalist-HK/mosdns-config/assets/125388319/d6245f0a-7380-4189-9849-749906f891cc)
2.clash日志里显示本地直连超时
![image](https://github.com/Journalist-HK/mosdns-config/assets/125388319/696fedba-4b99-4c85-83f1-cbfa5f7ef183)

**Comment by Journalist-HK** [comment]
1. 我没有办法保证上游的稳定性，你可以更换上游或者为某个上游添加 socks5 代理。[官方文档](https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/ru-he-pei-zhi-mosdns/ke-zhi-hang-cha-jian#forward)
2. 从截图不能看出是否是 DNS 的问题，需要更详细的配置文件和日志。先尝试确定是哪个程序发起的连接。

**Comment by q259490476** [comment]
嗯，关于第二点其实是所有直连都是超时，不知道什么情况，根本测不出速度，用节点就没问题
![Screenshot_20240220_194119_Edge](https://github.com/Journalist-HK/mosdns-config/assets/125388319/6c063b9e-caa4-4059-9bed-cc9b8a8bd754)

**Comment by Journalist-HK** [comment]
我不清楚你具体的配置是怎样的。建议你先确保这样的规则能正常直连。

```yaml
mixed-port: 7890
allow-lan: true
# bind-address: '*'
mode: rule
log-level: info
ipv6: true
# external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: true
  default-nameserver: [223.5.5.5]
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - "*.localdomain"
    - "*.invalid"
    - "*.localhost"
    - "*.local"
    - "*.home.arpa"
    - WORKGROUP
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - 'time.*.*'
    - 'time.*.*.*'
    - 'ntp.*.*'
    - 'ntp.*.*.*'
    - '+.pool.ntp.org'
    - time1.cloud.tencent.com
    - localhost.ptlogin2.qq.com
    - 'localhost.sec.qq.com'
    - 'time-ios.apple.com'
    - 'swscan.apple.com'
    - "swquery.apple.com"
    - "swdownload.apple.com"
    - "swcdn.apple.com"
    - "swdist.apple.com"
    - 'mesu.apple.com'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'connect.rom.miui.com'
    - 'connectivitycheck.platform.hicloud.com'
    - 'wifi.vivo.com.cn'
    - 'lens.l.google.com'
    - '+.srv.nintendo.net'
    - 'xbox.*.microsoft.com'
    - 'xbox.*.*.microsoft.com'
    - '*.ipv6.microsoft.com'
    - '+.wns.windows.com'
    - '+.xboxlive.com'
    - '*.mcdn.bilivideo.cn'
    - 'Mijia Cloud'
    - 'local.adguard.org'
    - 'static.adtidy.org'
    # Wi-Fi Calling
    - '+.3gppnetwork.org'
    - 'doh.apad.pro'
    - '*.*.xns.one'
  nameserver:
    - '192.168.1.1' # 填你的 mosdns

rules:
    - 'MATCH,DIRECT'
```
