### ISSUE TITLE
gfw_sequence 有个疑问

### ISSUE THREAD

**Issue by Sereinfy** [Journalist-HK/mosdns-config#5]
```
  - tag: gfw_sequence # 处理 GFW 域名
    type: sequence
    args:
      - exec: jump remote_sequence
      - exec: jump change_cdn_ip_akamai
      - exec: jump change_cdn_ip_cf
      - exec: jump reforward_fastly_remote
      - exec: accept # 查询失败也会停止，防止后续查询回落到国内上游
```

非常感谢分享，我是在你基础上修改的
假设google.com 是可替换优选ip的。这里如果用openclash。拿到mosdns域名之后，会建立http请求，请求来到clash，匹配到规则判断走代理。clash会把google.com发给代理服务器，有代理服务器的dns获取google.com的ip。然后建立连接。（看不良林视频，也可能是我理解错了）。那么疑问产生了
gfw_sequence 里替换流程是不是没有意义。
由本机remote_sequence附加ecs_tw获取的ip。和代理服务器获取的ip 有可能不一样吧
如果非要优选的话，也应该在代理服务器上测速
```
  - tag: gfw_sequence # 处理 GFW 域名
    type: sequence
    args:
      - exec: jump remote_sequence
      - exec: jump has_resp_sequence
```
我觉得应该这样写。感谢大哥，有错误还请指正
