### ISSUE TITLE
增加本地运营商IPv6无法访问国内的一些网站taobao

### ISSUE THREAD

**Issue by llity** [Journalist-HK/mosdns-config#9]
注释下面的IPv6地址就能正常访问了
```
  - tag: "forward_local"
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "218.2.2.2" # 运营商 DNS，自行修改
        - addr: "218.4.4.4" # 运营商 DNS，自行修改
        - addr: "240e:5a::6666" # 运营商 DNS，自行修改
        - addr: "240e:5b::6666" # 运营商 DNS，自行修改
```
